name: 'Basic'

on: push

jobs:
  first:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
      - name: Say hello world 1
        shell: bash
        run: |
          generatedValue1=$(echo $RANDOM)
          
          echo $generatedValue1
          echo "GEN_VALUE_1=$generatedValue1" >> $GITHUB_ENV
      - name: Say hello world 2
        shell: pwsh
        run: |
          generatedValue2=$(Get-Random -Max 99999)
          
          echo "GEN_VALUE_2=$generatedValue2" >> | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

      - name: GET Hell world values
        shell: bash
        run: |
          echo "GEN_VALUE_1: $GEN_VALUE_1"
          echo "GEN_VALUE_2: ${{ env.GEN_VALUE_2 }}"