name: 'Basic'

on: 
  push:
    branches:
      - main

jobs:
  somabot:
    name: "쏘마 봇으로 메시지 보내기"
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Webex spage
        shell: bash
        run: |
          curl --location --request POST 'https://webexapis.com/v1/messages' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}' \
            --data-raw '{
              "roomId": "${{ secrets.WEBEX_ROOM_ID }}",
              "text": "안녕하세요 깃헙 액션에서 보내는 이진우봇입니다"
            }'